### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by kamilsa** [soramitsu/soralog#1]
https://github.com/xDimon/soralog/blob/ae4f55d62d597dea3abe92e03fe67bfbf9cd7ee9/include/soralog/logging_system.hpp#L40

I would move comments from here to the parent's class

**Comment by kamilsa** [comment]
Also comments here https://github.com/xDimon/soralog/blob/5fc8067ffd0f93924b5ec459fb9968c6da8be2d0/include/soralog/configurator.hpp#L14

**Comment by kamilsa** [comment]
And here
https://github.com/xDimon/soralog/blob/5fc8067ffd0f93924b5ec459fb9968c6da8be2d0/include/soralog/impl/fallback_configurator.hpp#L15

**Comment by kamilsa** [comment]
Please add option to print thread id

**Comment by xDimon** [comment]
> https://github.com/xDimon/soralog/blob/ae4f55d62d597dea3abe92e03fe67bfbf9cd7ee9/include/soralog/logging_system.hpp#L40
> 
> I would move comments from here to the parent's class

Base class does not have this method.
